### PR TITLE
Fixed item names & lores always being italic

### PR DESCRIPTION
**Pull request by Ultra741**
Small bugfix.

### CODE REVIEW

**Comment by MarvelousAnything** [comment]
Could you provide more clarification/details for this PR? Also, could you clean up your commits? Ensure you create a new branch for your changes when doing a PR. The "added glow method" commit was already merged into master.

**Comment by Ultra741** [comment]
> Could you provide more clarification/details for this PR? Also, could you clean up your commits? Ensure you create a new branch for your changes when doing a PR. The "added glow method" commit was already merged into master.

I'm encountering an issue where item names and lores are always italic. I did some research and apparently, you need to explicitly set the names/lores to non-italic.

**Comment by MarvelousAnything** [comment]
Ok. And have you checked to make sure that this does not have any unintended side effects? Can the lore text still be in italics? You are setting the TextDecoration state to FALSE for italics. This implies that if you want the item name/lore to be italicized, it will remove that.

**Comment by Ultra741** [comment]
> Ok. And have you checked to make sure that this does not have any unintended side effects? Can the lore text still be in italics? You are setting the TextDecoration state to FALSE for italics. This implies that if you want the item name/lore to be italicized, it will remove that.

I haven't though of that, but I can't think of anything else that will fix this.

**Comment by MarvelousAnything** [comment]
You may need to pass the Text component that you want to use with italics disabled. It is inconvenient, but we cannot modify this behavior for all items. I would consider this technically a breaking change since it alters expected behavior.

**Comment by MarvelousAnything** [comment]
Upon further review, we have concluded that the text-decoration stuff is just weird. The Kyori adventure text API is wonky. Marcus just pushed a change to the Text class that fixes this anomaly for all text, not just item names and lore in [315263f](https://github.com/MarcusSlover/Plus/commit/315263f4c53bb2649cf9503385afba074d38f6db).

**Pull request closed without merging**
